### ISSUE TITLE
Nybus 1.0

### ISSUE THREAD

**Issue by Kralizek** [Nybus-project/Nybus#19]
This issue is to track the tasks needed to go live with the version 1.0

* [x] Push current `master` into a `v0` branch
* [x] Create new build script for AppVeyor
* [x] Update README.md file
* [x] Finalize unit tests #22 
* [x] Expand integration tests for `Nybus` #23 
* [x] Add integration tests for RabbitMq engine #24 
* [x] Add support for automatic versioning #21 
* [x] Final check
* [x] Force `v1` branch onto `master`
